/*
 * Copyright (c) 2026 Ugwu Valentine Nnannaya.
 * All rights reserved.
 *
 * This project is proprietary. Unauthorized copying,
 * modification, or distribution is not permitted.
 */

#include <cstring>
#include <sstream>

#include "descriptor.hpp"
#include "policy.hpp"

#define INSERT_RELATION(rel, node_a, node_b) nn_insert_relation(edges+rel, edges+rel##_INV, nodes+node_a, nodes+node_b)
#define INSERT_ATTRIBUTE(attr, node_id) nn_insert_attribute(attr, node_id, attributes)
#define QUALIFY_SQUARE(Sq) \
                switch (brd.mailbox[Sq]) { \
                case 0x1: INSERT_ATTRIBUTE(FRIEND_PAWN, Sq); break; \
                case 0x2: INSERT_ATTRIBUTE(FRIEND_KNIGHT, Sq); break; \
                case 0x3: INSERT_ATTRIBUTE(FRIEND_BISHOP, Sq); break; \
                case 0x4: INSERT_ATTRIBUTE(FRIEND_ROOK, Sq); break; \
                case 0x5: INSERT_ATTRIBUTE(FRIEND_QUEEN, Sq); break; \
                case 0x6: INSERT_ATTRIBUTE(FRIEND_KING, Sq); break; \
                case 0x8: INSERT_ATTRIBUTE(ENEMY_PAWN, Sq); break; \
                case 0x9: INSERT_ATTRIBUTE(ENEMY_KNIGHT, Sq); break; \
                case 0xa: INSERT_ATTRIBUTE(ENEMY_BISHOP, Sq); break; \
                case 0xb: INSERT_ATTRIBUTE(ENEMY_ROOK, Sq); break; \
                case 0xc: INSERT_ATTRIBUTE(ENEMY_QUEEN, Sq); break; \
                case 0xd: INSERT_ATTRIBUTE(ENEMY_KING, Sq); break; \
                default: INSERT_ATTRIBUTE(EMPTY, Sq); \
                }

enum node_type : nn_uint_t 
{
        S01, S02, S03, S04, S05, S06, S07, S08
    ,   S09, S10, S11, S12, S13, S14, S15, S16
    ,   S17, S18, S19, S20, S21, S22, S23, S24
    ,   S25, S26, S27, S28, S29, S30, S31, S32
    ,   S33, S34, S35, S36, S37, S38, S39, S40
    ,   S41, S42, S43, S44, S45, S46, S47, S48
    ,   S49, S50, S51, S52, S53, S54, S55, S56
    ,   S57, S58, S59, S60, S61, S62, S63, S64

    ,   R1, R2, R3, R4, R5, R6, R7, R8
    ,   FA, FB, FC, FD, FE, FF, FG, FH

    ,   D01, D02, D03, D04, D05, D06, D07, D08, D09, D10
    ,   D11, D12, D13, D14, D15, D16, D17, D18, D19, D20
    ,   D21, D22, D23, D24, D25, D26, D27, D28, D29, D30
};

enum edge_type : nn_uint_t
{
        ON
    ,   ON_INV
    ,   ADJACENT
    ,   ADJACENT_INV=ADJACENT
    ,   ABOVE
    ,   ABOVE_INV
    ,   NXT_TO
    ,   NXT_TO_INV
};

enum attribute_type : nn_uint_t 
{
        FRIEND_PAWN, FRIEND_KNIGHT, FRIEND_BISHOP, FRIEND_ROOK, FRIEND_QUEEN, FRIEND_KING
    ,   FRIEND_OO, FRIEND_OOO
    ,   ENEMY_PAWN, ENEMY_KNIGHT, ENEMY_BISHOP, ENEMY_ROOK, ENEMY_QUEEN, ENEMY_KING
    ,   ENEMY_OO, ENEMY_OOO
    ,   ROW, COLUMN, DIAGONAL, ANTI_DIAGONAL, ENPASSANT, EMPTY
};

template<class T>
inline T yield(std::stringstream& ss)
{
    T value; ss >> value;
    return value;
}

board::board(const std::string& fen)
    :   mailbox {}
    ,   ep_file(-1)
    ,   friend_has_oo(0)
    ,   friend_has_ooo(0)
    ,   enemy_has_oo(0)
    ,   enemy_has_ooo(0)
{
    bool iw;
    char ch;
    std::stringstream ss(fen);

    ss >> std::noskipws;

    for (auto sq = 56; (ss >> ch) && !isspace(ch); )
    {
        if (isdigit(ch) && ch != '0')  
        {
            sq += (int)(ch - '0');
        }
        else if (ch  ==  '/') {

            sq -= 16;
        }

        else  {

            if (ch=='P') mailbox[sq]=0x1;
            if (ch=='N') mailbox[sq]=0x2;
            if (ch=='B') mailbox[sq]=0x3;
            if (ch=='R') mailbox[sq]=0x4;
            if (ch=='Q') mailbox[sq]=0x5;
            if (ch=='K') mailbox[sq]=0x6;
            if (ch=='p') mailbox[sq]=0x8;
            if (ch=='n') mailbox[sq]=0x9;
            if (ch=='b') mailbox[sq]=0xa;
            if (ch=='r') mailbox[sq]=0xb;
            if (ch=='q') mailbox[sq]=0xc;
            if (ch=='k') mailbox[sq]=0xd;

            sq++;
        }
    }

    iw=yield<char>(ss)=='b'?false:true;

    yield<char>(ss);

    while ((ss >> ch) && !isspace(ch)) 
    {
        if (ch == 'K') friend_has_oo=true;
        if (ch == 'Q') friend_has_ooo=true;
        if (ch == 'k') enemy_has_oo=true;
        if (ch == 'q') enemy_has_ooo=true;
    }

    if ((ss >> ch) && isalpha(ch))
    {
        ep_file=(int)(ch-'a'), yield<char>(ss);
    }

    if (!iw) {
        std::swap(friend_has_ooo, enemy_has_ooo);
        std::swap(friend_has_oo, enemy_has_oo);

        for (int i=0; i < 32; i++) {
            std::swap(mailbox[i], mailbox[i^56]);
        }
    }
}

descriptor::descriptor
    (
            const board& brd
        ,   const move moves[]
        ,   int mcount
    )
        :   b(brd)
        ,   moves_ {}
        ,   mcount_(mcount)
        ,   attributes_data {}
        ,   relations {}
        ,   pairs {}
        ,   edges {}
        ,   nodes {}
        ,   attributes {}
        ,   graphnet {
                    .edges=edges
                ,   .nodes=nodes
                ,   .node_count=NODE_COUNT
                ,   .edge_count=EDGE_COUNT
            }
{
    // setup nodes
    for (nn_uint16_t i=0; i < NODE_COUNT; i++)
    {
        attributes[i].attributes=attributes_data[i];
        attributes[i].attributes_count=0;

        nodes[i].relations=relations[i];
        nodes[i].id=i;
    }

    // setup edges
    for (nn_uint16_t i=0; i < EDGE_COUNT; i++)
    {
        edges[i].pairs=pairs[i];
        edges[i].id=i;
    }

    nn_zero_graphnet(&graphnet);

    std::memcpy(moves_, moves, sizeof(move) * mcount);

    INSERT_ATTRIBUTE(DIAGONAL, D01),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D16);
    INSERT_ATTRIBUTE(DIAGONAL, D02),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D17);
    INSERT_ATTRIBUTE(DIAGONAL, D03),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D18);
    INSERT_ATTRIBUTE(DIAGONAL, D04),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D19);
    INSERT_ATTRIBUTE(DIAGONAL, D05),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D20);
    INSERT_ATTRIBUTE(DIAGONAL, D06),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D21);
    INSERT_ATTRIBUTE(DIAGONAL, D07),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D22);
    INSERT_ATTRIBUTE(DIAGONAL, D08),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D23);
    INSERT_ATTRIBUTE(DIAGONAL, D09),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D24);
    INSERT_ATTRIBUTE(DIAGONAL, D10),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D25);
    INSERT_ATTRIBUTE(DIAGONAL, D11),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D26);
    INSERT_ATTRIBUTE(DIAGONAL, D12),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D27);
    INSERT_ATTRIBUTE(DIAGONAL, D13),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D28);
    INSERT_ATTRIBUTE(DIAGONAL, D14),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D29);
    INSERT_ATTRIBUTE(DIAGONAL, D15),  INSERT_ATTRIBUTE(ANTI_DIAGONAL, D30);

    INSERT_ATTRIBUTE(ROW, R1),  INSERT_ATTRIBUTE(COLUMN, FA);
    INSERT_ATTRIBUTE(ROW, R2),  INSERT_ATTRIBUTE(COLUMN, FB);
    INSERT_ATTRIBUTE(ROW, R3),  INSERT_ATTRIBUTE(COLUMN, FC);
    INSERT_ATTRIBUTE(ROW, R4),  INSERT_ATTRIBUTE(COLUMN, FD);
    INSERT_ATTRIBUTE(ROW, R5),  INSERT_ATTRIBUTE(COLUMN, FE);
    INSERT_ATTRIBUTE(ROW, R6),  INSERT_ATTRIBUTE(COLUMN, FF);
    INSERT_ATTRIBUTE(ROW, R7),  INSERT_ATTRIBUTE(COLUMN, FG);
    INSERT_ATTRIBUTE(ROW, R8),  INSERT_ATTRIBUTE(COLUMN, FH);

    if (brd.friend_has_oo ) INSERT_ATTRIBUTE(FRIEND_OO , S05);
    if (brd.friend_has_ooo) INSERT_ATTRIBUTE(FRIEND_OOO, S05);
    if (brd. enemy_has_oo ) INSERT_ATTRIBUTE( ENEMY_OO , S61);
    if (brd. enemy_has_ooo) INSERT_ATTRIBUTE( ENEMY_OOO, S61);

    switch (brd.ep_file)
    {
    case 0: INSERT_ATTRIBUTE(ENPASSANT, FA); break;
    case 1: INSERT_ATTRIBUTE(ENPASSANT, FB); break;
    case 2: INSERT_ATTRIBUTE(ENPASSANT, FC); break;
    case 3: INSERT_ATTRIBUTE(ENPASSANT, FD); break;
    case 4: INSERT_ATTRIBUTE(ENPASSANT, FE); break;
    case 5: INSERT_ATTRIBUTE(ENPASSANT, FF); break;
    case 6: INSERT_ATTRIBUTE(ENPASSANT, FG); break;
    case 7: INSERT_ATTRIBUTE(ENPASSANT, FH); break;
    default:;
    }

    QUALIFY_SQUARE(S01);  QUALIFY_SQUARE(S33); 
    QUALIFY_SQUARE(S02);  QUALIFY_SQUARE(S34); 
    QUALIFY_SQUARE(S03);  QUALIFY_SQUARE(S35); 
    QUALIFY_SQUARE(S04);  QUALIFY_SQUARE(S36); 
    QUALIFY_SQUARE(S05);  QUALIFY_SQUARE(S37); 
    QUALIFY_SQUARE(S06);  QUALIFY_SQUARE(S38); 
    QUALIFY_SQUARE(S07);  QUALIFY_SQUARE(S39); 
    QUALIFY_SQUARE(S08);  QUALIFY_SQUARE(S40); 
    QUALIFY_SQUARE(S09);  QUALIFY_SQUARE(S41); 
    QUALIFY_SQUARE(S10);  QUALIFY_SQUARE(S42); 
    QUALIFY_SQUARE(S11);  QUALIFY_SQUARE(S43); 
    QUALIFY_SQUARE(S12);  QUALIFY_SQUARE(S44); 
    QUALIFY_SQUARE(S13);  QUALIFY_SQUARE(S45); 
    QUALIFY_SQUARE(S14);  QUALIFY_SQUARE(S46); 
    QUALIFY_SQUARE(S15);  QUALIFY_SQUARE(S47); 
    QUALIFY_SQUARE(S16);  QUALIFY_SQUARE(S48); 
    QUALIFY_SQUARE(S17);  QUALIFY_SQUARE(S49); 
    QUALIFY_SQUARE(S18);  QUALIFY_SQUARE(S50); 
    QUALIFY_SQUARE(S19);  QUALIFY_SQUARE(S51); 
    QUALIFY_SQUARE(S20);  QUALIFY_SQUARE(S52); 
    QUALIFY_SQUARE(S21);  QUALIFY_SQUARE(S53); 
    QUALIFY_SQUARE(S22);  QUALIFY_SQUARE(S54); 
    QUALIFY_SQUARE(S23);  QUALIFY_SQUARE(S55); 
    QUALIFY_SQUARE(S24);  QUALIFY_SQUARE(S56); 
    QUALIFY_SQUARE(S25);  QUALIFY_SQUARE(S57); 
    QUALIFY_SQUARE(S26);  QUALIFY_SQUARE(S58); 
    QUALIFY_SQUARE(S27);  QUALIFY_SQUARE(S59); 
    QUALIFY_SQUARE(S28);  QUALIFY_SQUARE(S60); 
    QUALIFY_SQUARE(S29);  QUALIFY_SQUARE(S61); 
    QUALIFY_SQUARE(S30);  QUALIFY_SQUARE(S62); 
    QUALIFY_SQUARE(S31);  QUALIFY_SQUARE(S63); 
    QUALIFY_SQUARE(S32);  QUALIFY_SQUARE(S64);

    INSERT_RELATION(ON, S01, R1),  INSERT_RELATION(ON, S01, FA);
    INSERT_RELATION(ON, S02, R1),  INSERT_RELATION(ON, S09, FA);
    INSERT_RELATION(ON, S03, R1),  INSERT_RELATION(ON, S17, FA);
    INSERT_RELATION(ON, S04, R1),  INSERT_RELATION(ON, S25, FA);
    INSERT_RELATION(ON, S05, R1),  INSERT_RELATION(ON, S33, FA);
    INSERT_RELATION(ON, S06, R1),  INSERT_RELATION(ON, S41, FA);
    INSERT_RELATION(ON, S07, R1),  INSERT_RELATION(ON, S49, FA);
    INSERT_RELATION(ON, S08, R1),  INSERT_RELATION(ON, S57, FA);
    INSERT_RELATION(ON, S09, R2),  INSERT_RELATION(ON, S02, FB);
    INSERT_RELATION(ON, S10, R2),  INSERT_RELATION(ON, S10, FB);
    INSERT_RELATION(ON, S11, R2),  INSERT_RELATION(ON, S18, FB);
    INSERT_RELATION(ON, S12, R2),  INSERT_RELATION(ON, S26, FB);
    INSERT_RELATION(ON, S13, R2),  INSERT_RELATION(ON, S34, FB);
    INSERT_RELATION(ON, S14, R2),  INSERT_RELATION(ON, S42, FB);
    INSERT_RELATION(ON, S15, R2),  INSERT_RELATION(ON, S50, FB);
    INSERT_RELATION(ON, S16, R2),  INSERT_RELATION(ON, S58, FB);
    INSERT_RELATION(ON, S17, R3),  INSERT_RELATION(ON, S03, FC);
    INSERT_RELATION(ON, S18, R3),  INSERT_RELATION(ON, S11, FC);
    INSERT_RELATION(ON, S19, R3),  INSERT_RELATION(ON, S19, FC);
    INSERT_RELATION(ON, S20, R3),  INSERT_RELATION(ON, S27, FC);
    INSERT_RELATION(ON, S21, R3),  INSERT_RELATION(ON, S35, FC);
    INSERT_RELATION(ON, S22, R3),  INSERT_RELATION(ON, S43, FC);
    INSERT_RELATION(ON, S23, R3),  INSERT_RELATION(ON, S51, FC);
    INSERT_RELATION(ON, S24, R3),  INSERT_RELATION(ON, S59, FC);
    INSERT_RELATION(ON, S25, R4),  INSERT_RELATION(ON, S04, FD);
    INSERT_RELATION(ON, S26, R4),  INSERT_RELATION(ON, S12, FD);
    INSERT_RELATION(ON, S27, R4),  INSERT_RELATION(ON, S20, FD);
    INSERT_RELATION(ON, S28, R4),  INSERT_RELATION(ON, S28, FD);
    INSERT_RELATION(ON, S29, R4),  INSERT_RELATION(ON, S36, FD);
    INSERT_RELATION(ON, S30, R4),  INSERT_RELATION(ON, S44, FD);
    INSERT_RELATION(ON, S31, R4),  INSERT_RELATION(ON, S52, FD);
    INSERT_RELATION(ON, S32, R4),  INSERT_RELATION(ON, S60, FD);
    INSERT_RELATION(ON, S33, R5),  INSERT_RELATION(ON, S05, FE);
    INSERT_RELATION(ON, S34, R5),  INSERT_RELATION(ON, S13, FE);
    INSERT_RELATION(ON, S35, R5),  INSERT_RELATION(ON, S21, FE);
    INSERT_RELATION(ON, S36, R5),  INSERT_RELATION(ON, S29, FE);
    INSERT_RELATION(ON, S37, R5),  INSERT_RELATION(ON, S37, FE);
    INSERT_RELATION(ON, S38, R5),  INSERT_RELATION(ON, S45, FE);
    INSERT_RELATION(ON, S39, R5),  INSERT_RELATION(ON, S53, FE);
    INSERT_RELATION(ON, S40, R5),  INSERT_RELATION(ON, S61, FE);
    INSERT_RELATION(ON, S41, R6),  INSERT_RELATION(ON, S06, FF);
    INSERT_RELATION(ON, S42, R6),  INSERT_RELATION(ON, S14, FF);
    INSERT_RELATION(ON, S43, R6),  INSERT_RELATION(ON, S22, FF);
    INSERT_RELATION(ON, S44, R6),  INSERT_RELATION(ON, S30, FF);
    INSERT_RELATION(ON, S45, R6),  INSERT_RELATION(ON, S38, FF);
    INSERT_RELATION(ON, S46, R6),  INSERT_RELATION(ON, S46, FF);
    INSERT_RELATION(ON, S47, R6),  INSERT_RELATION(ON, S54, FF);
    INSERT_RELATION(ON, S48, R6),  INSERT_RELATION(ON, S62, FF);
    INSERT_RELATION(ON, S49, R7),  INSERT_RELATION(ON, S07, FG);
    INSERT_RELATION(ON, S50, R7),  INSERT_RELATION(ON, S15, FG);
    INSERT_RELATION(ON, S51, R7),  INSERT_RELATION(ON, S23, FG);
    INSERT_RELATION(ON, S52, R7),  INSERT_RELATION(ON, S31, FG);
    INSERT_RELATION(ON, S53, R7),  INSERT_RELATION(ON, S39, FG);
    INSERT_RELATION(ON, S54, R7),  INSERT_RELATION(ON, S47, FG);
    INSERT_RELATION(ON, S55, R7),  INSERT_RELATION(ON, S55, FG);
    INSERT_RELATION(ON, S56, R7),  INSERT_RELATION(ON, S63, FG);
    INSERT_RELATION(ON, S57, R8),  INSERT_RELATION(ON, S08, FH);
    INSERT_RELATION(ON, S58, R8),  INSERT_RELATION(ON, S16, FH);
    INSERT_RELATION(ON, S59, R8),  INSERT_RELATION(ON, S24, FH);
    INSERT_RELATION(ON, S60, R8),  INSERT_RELATION(ON, S32, FH);
    INSERT_RELATION(ON, S61, R8),  INSERT_RELATION(ON, S40, FH);
    INSERT_RELATION(ON, S62, R8),  INSERT_RELATION(ON, S48, FH);
    INSERT_RELATION(ON, S63, R8),  INSERT_RELATION(ON, S56, FH);
    INSERT_RELATION(ON, S64, R8),  INSERT_RELATION(ON, S64, FH);

    INSERT_RELATION(ON, S01, D01),  INSERT_RELATION(ON, S33, D05);
    INSERT_RELATION(ON, S02, D02),  INSERT_RELATION(ON, S34, D06);
    INSERT_RELATION(ON, S03, D03),  INSERT_RELATION(ON, S35, D07);
    INSERT_RELATION(ON, S04, D04),  INSERT_RELATION(ON, S36, D08);
    INSERT_RELATION(ON, S05, D05),  INSERT_RELATION(ON, S37, D09);
    INSERT_RELATION(ON, S06, D06),  INSERT_RELATION(ON, S38, D10);
    INSERT_RELATION(ON, S07, D07),  INSERT_RELATION(ON, S39, D11);
    INSERT_RELATION(ON, S08, D08),  INSERT_RELATION(ON, S40, D12);
    INSERT_RELATION(ON, S09, D02),  INSERT_RELATION(ON, S41, D06);
    INSERT_RELATION(ON, S10, D03),  INSERT_RELATION(ON, S42, D07);
    INSERT_RELATION(ON, S11, D04),  INSERT_RELATION(ON, S43, D08);
    INSERT_RELATION(ON, S12, D05),  INSERT_RELATION(ON, S44, D09);
    INSERT_RELATION(ON, S13, D06),  INSERT_RELATION(ON, S45, D10);
    INSERT_RELATION(ON, S14, D07),  INSERT_RELATION(ON, S46, D11);
    INSERT_RELATION(ON, S15, D08),  INSERT_RELATION(ON, S47, D12);
    INSERT_RELATION(ON, S16, D09),  INSERT_RELATION(ON, S48, D13);
    INSERT_RELATION(ON, S17, D03),  INSERT_RELATION(ON, S49, D07);
    INSERT_RELATION(ON, S18, D04),  INSERT_RELATION(ON, S50, D08);
    INSERT_RELATION(ON, S19, D05),  INSERT_RELATION(ON, S51, D09);
    INSERT_RELATION(ON, S20, D06),  INSERT_RELATION(ON, S52, D10);
    INSERT_RELATION(ON, S21, D07),  INSERT_RELATION(ON, S53, D11);
    INSERT_RELATION(ON, S22, D08),  INSERT_RELATION(ON, S54, D12);
    INSERT_RELATION(ON, S23, D09),  INSERT_RELATION(ON, S55, D13);
    INSERT_RELATION(ON, S24, D10),  INSERT_RELATION(ON, S56, D14);
    INSERT_RELATION(ON, S25, D04),  INSERT_RELATION(ON, S57, D08);
    INSERT_RELATION(ON, S26, D05),  INSERT_RELATION(ON, S58, D09);
    INSERT_RELATION(ON, S27, D06),  INSERT_RELATION(ON, S59, D10);
    INSERT_RELATION(ON, S28, D07),  INSERT_RELATION(ON, S60, D11);
    INSERT_RELATION(ON, S29, D08),  INSERT_RELATION(ON, S61, D12);
    INSERT_RELATION(ON, S30, D09),  INSERT_RELATION(ON, S62, D13);
    INSERT_RELATION(ON, S31, D10),  INSERT_RELATION(ON, S63, D14);
    INSERT_RELATION(ON, S32, D11),  INSERT_RELATION(ON, S64, D15);

    INSERT_RELATION(ON, S01, D23),  INSERT_RELATION(ON, S33, D19);
    INSERT_RELATION(ON, S02, D24),  INSERT_RELATION(ON, S34, D20);
    INSERT_RELATION(ON, S03, D25),  INSERT_RELATION(ON, S35, D21);
    INSERT_RELATION(ON, S04, D26),  INSERT_RELATION(ON, S36, D22);
    INSERT_RELATION(ON, S05, D27),  INSERT_RELATION(ON, S37, D23);
    INSERT_RELATION(ON, S06, D28),  INSERT_RELATION(ON, S38, D24);
    INSERT_RELATION(ON, S07, D29),  INSERT_RELATION(ON, S39, D25);
    INSERT_RELATION(ON, S08, D30),  INSERT_RELATION(ON, S40, D26);
    INSERT_RELATION(ON, S09, D22),  INSERT_RELATION(ON, S41, D18);
    INSERT_RELATION(ON, S10, D23),  INSERT_RELATION(ON, S42, D19);
    INSERT_RELATION(ON, S11, D24),  INSERT_RELATION(ON, S43, D20);
    INSERT_RELATION(ON, S12, D25),  INSERT_RELATION(ON, S44, D21);
    INSERT_RELATION(ON, S13, D26),  INSERT_RELATION(ON, S45, D22);
    INSERT_RELATION(ON, S14, D27),  INSERT_RELATION(ON, S46, D23);
    INSERT_RELATION(ON, S15, D28),  INSERT_RELATION(ON, S47, D24);
    INSERT_RELATION(ON, S16, D29),  INSERT_RELATION(ON, S48, D25);
    INSERT_RELATION(ON, S17, D21),  INSERT_RELATION(ON, S49, D17);
    INSERT_RELATION(ON, S18, D22),  INSERT_RELATION(ON, S50, D18);
    INSERT_RELATION(ON, S19, D23),  INSERT_RELATION(ON, S51, D19);
    INSERT_RELATION(ON, S20, D24),  INSERT_RELATION(ON, S52, D20);
    INSERT_RELATION(ON, S21, D25),  INSERT_RELATION(ON, S53, D21);
    INSERT_RELATION(ON, S22, D26),  INSERT_RELATION(ON, S54, D22);
    INSERT_RELATION(ON, S23, D27),  INSERT_RELATION(ON, S55, D23);
    INSERT_RELATION(ON, S24, D28),  INSERT_RELATION(ON, S56, D24);
    INSERT_RELATION(ON, S25, D20),  INSERT_RELATION(ON, S57, D16);
    INSERT_RELATION(ON, S26, D21),  INSERT_RELATION(ON, S58, D17);
    INSERT_RELATION(ON, S27, D22),  INSERT_RELATION(ON, S59, D18);
    INSERT_RELATION(ON, S28, D23),  INSERT_RELATION(ON, S60, D19);
    INSERT_RELATION(ON, S29, D24),  INSERT_RELATION(ON, S61, D20);
    INSERT_RELATION(ON, S30, D25),  INSERT_RELATION(ON, S62, D21);
    INSERT_RELATION(ON, S31, D26),  INSERT_RELATION(ON, S63, D22);
    INSERT_RELATION(ON, S32, D27),  INSERT_RELATION(ON, S64, D23);

    INSERT_RELATION(NXT_TO, S02, S01),  INSERT_RELATION(NXT_TO, S34, S33);
    INSERT_RELATION(NXT_TO, S03, S02),  INSERT_RELATION(NXT_TO, S35, S34);
    INSERT_RELATION(NXT_TO, S04, S03),  INSERT_RELATION(NXT_TO, S36, S35);
    INSERT_RELATION(NXT_TO, S05, S04),  INSERT_RELATION(NXT_TO, S37, S36);
    INSERT_RELATION(NXT_TO, S06, S05),  INSERT_RELATION(NXT_TO, S38, S37);
    INSERT_RELATION(NXT_TO, S07, S06),  INSERT_RELATION(NXT_TO, S39, S38);
    INSERT_RELATION(NXT_TO, S08, S07),  INSERT_RELATION(NXT_TO, S40, S39);
    
    INSERT_RELATION(NXT_TO, S10, S09),  INSERT_RELATION(NXT_TO, S42, S41);
    INSERT_RELATION(NXT_TO, S11, S10),  INSERT_RELATION(NXT_TO, S43, S42);
    INSERT_RELATION(NXT_TO, S12, S11),  INSERT_RELATION(NXT_TO, S44, S43);
    INSERT_RELATION(NXT_TO, S13, S12),  INSERT_RELATION(NXT_TO, S45, S44);
    INSERT_RELATION(NXT_TO, S14, S13),  INSERT_RELATION(NXT_TO, S46, S45);
    INSERT_RELATION(NXT_TO, S15, S14),  INSERT_RELATION(NXT_TO, S47, S46);
    INSERT_RELATION(NXT_TO, S16, S15),  INSERT_RELATION(NXT_TO, S48, S47);

    INSERT_RELATION(NXT_TO, S18, S17),  INSERT_RELATION(NXT_TO, S50, S49);
    INSERT_RELATION(NXT_TO, S19, S18),  INSERT_RELATION(NXT_TO, S51, S50);
    INSERT_RELATION(NXT_TO, S20, S19),  INSERT_RELATION(NXT_TO, S52, S51);
    INSERT_RELATION(NXT_TO, S21, S20),  INSERT_RELATION(NXT_TO, S53, S52);
    INSERT_RELATION(NXT_TO, S22, S21),  INSERT_RELATION(NXT_TO, S54, S53);
    INSERT_RELATION(NXT_TO, S23, S22),  INSERT_RELATION(NXT_TO, S55, S54);
    INSERT_RELATION(NXT_TO, S24, S23),  INSERT_RELATION(NXT_TO, S56, S55);

    INSERT_RELATION(NXT_TO, S26, S25);  INSERT_RELATION(NXT_TO, S58, S57);
    INSERT_RELATION(NXT_TO, S27, S26);  INSERT_RELATION(NXT_TO, S59, S58);
    INSERT_RELATION(NXT_TO, S28, S27);  INSERT_RELATION(NXT_TO, S60, S59);
    INSERT_RELATION(NXT_TO, S29, S28);  INSERT_RELATION(NXT_TO, S61, S60);
    INSERT_RELATION(NXT_TO, S30, S29);  INSERT_RELATION(NXT_TO, S62, S61);
    INSERT_RELATION(NXT_TO, S31, S30);  INSERT_RELATION(NXT_TO, S63, S62);
    INSERT_RELATION(NXT_TO, S32, S31);  INSERT_RELATION(NXT_TO, S64, S63);

    INSERT_RELATION(ABOVE, S09, S01);  INSERT_RELATION(ABOVE, S13, S05);
    INSERT_RELATION(ABOVE, S17, S09);  INSERT_RELATION(ABOVE, S21, S13);
    INSERT_RELATION(ABOVE, S25, S17);  INSERT_RELATION(ABOVE, S29, S21);
    INSERT_RELATION(ABOVE, S33, S25);  INSERT_RELATION(ABOVE, S37, S29);
    INSERT_RELATION(ABOVE, S41, S33);  INSERT_RELATION(ABOVE, S45, S37);
    INSERT_RELATION(ABOVE, S49, S41);  INSERT_RELATION(ABOVE, S53, S45);
    INSERT_RELATION(ABOVE, S57, S49);  INSERT_RELATION(ABOVE, S61, S53);

    INSERT_RELATION(ABOVE, S10, S02);  INSERT_RELATION(ABOVE, S14, S06);
    INSERT_RELATION(ABOVE, S18, S10);  INSERT_RELATION(ABOVE, S22, S14);
    INSERT_RELATION(ABOVE, S26, S18);  INSERT_RELATION(ABOVE, S30, S22);
    INSERT_RELATION(ABOVE, S34, S26);  INSERT_RELATION(ABOVE, S38, S30);
    INSERT_RELATION(ABOVE, S42, S34);  INSERT_RELATION(ABOVE, S46, S38);
    INSERT_RELATION(ABOVE, S50, S42);  INSERT_RELATION(ABOVE, S54, S46);
    INSERT_RELATION(ABOVE, S58, S50);  INSERT_RELATION(ABOVE, S62, S54);

    INSERT_RELATION(ABOVE, S11, S03);  INSERT_RELATION(ABOVE, S15, S07);
    INSERT_RELATION(ABOVE, S19, S11);  INSERT_RELATION(ABOVE, S23, S15);
    INSERT_RELATION(ABOVE, S27, S19);  INSERT_RELATION(ABOVE, S31, S23);
    INSERT_RELATION(ABOVE, S35, S27);  INSERT_RELATION(ABOVE, S39, S31);
    INSERT_RELATION(ABOVE, S43, S35);  INSERT_RELATION(ABOVE, S47, S39);
    INSERT_RELATION(ABOVE, S51, S43);  INSERT_RELATION(ABOVE, S55, S47);
    INSERT_RELATION(ABOVE, S59, S51);  INSERT_RELATION(ABOVE, S63, S55);

    INSERT_RELATION(ABOVE, S12, S04);  INSERT_RELATION(ABOVE, S16, S08);
    INSERT_RELATION(ABOVE, S20, S12);  INSERT_RELATION(ABOVE, S24, S16);
    INSERT_RELATION(ABOVE, S28, S20);  INSERT_RELATION(ABOVE, S32, S24);
    INSERT_RELATION(ABOVE, S36, S28);  INSERT_RELATION(ABOVE, S40, S32);
    INSERT_RELATION(ABOVE, S44, S36);  INSERT_RELATION(ABOVE, S48, S40);
    INSERT_RELATION(ABOVE, S52, S44);  INSERT_RELATION(ABOVE, S56, S48);
    INSERT_RELATION(ABOVE, S60, S52);  INSERT_RELATION(ABOVE, S64, S56);

    INSERT_RELATION(ADJACENT, D01, D02),  INSERT_RELATION(ADJACENT, D16, D17);
    INSERT_RELATION(ADJACENT, D02, D03),  INSERT_RELATION(ADJACENT, D17, D18);
    INSERT_RELATION(ADJACENT, D03, D04),  INSERT_RELATION(ADJACENT, D18, D19);
    INSERT_RELATION(ADJACENT, D04, D05),  INSERT_RELATION(ADJACENT, D19, D20);
    INSERT_RELATION(ADJACENT, D05, D06),  INSERT_RELATION(ADJACENT, D20, D21);
    INSERT_RELATION(ADJACENT, D06, D07),  INSERT_RELATION(ADJACENT, D21, D22);
    INSERT_RELATION(ADJACENT, D07, D08),  INSERT_RELATION(ADJACENT, D22, D23);
    INSERT_RELATION(ADJACENT, D08, D09),  INSERT_RELATION(ADJACENT, D23, D24);
    INSERT_RELATION(ADJACENT, D09, D10),  INSERT_RELATION(ADJACENT, D24, D25);
    INSERT_RELATION(ADJACENT, D10, D11),  INSERT_RELATION(ADJACENT, D25, D26);
    INSERT_RELATION(ADJACENT, D11, D12),  INSERT_RELATION(ADJACENT, D26, D27);
    INSERT_RELATION(ADJACENT, D12, D13),  INSERT_RELATION(ADJACENT, D27, D28);
    INSERT_RELATION(ADJACENT, D13, D14),  INSERT_RELATION(ADJACENT, D28, D29);
    INSERT_RELATION(ADJACENT, D14, D15),  INSERT_RELATION(ADJACENT, D29, D30);

    INSERT_RELATION(ADJACENT, R1, R2),  INSERT_RELATION(ADJACENT, FA, FB);
    INSERT_RELATION(ADJACENT, R2, R3),  INSERT_RELATION(ADJACENT, FB, FC);
    INSERT_RELATION(ADJACENT, R3, R4),  INSERT_RELATION(ADJACENT, FC, FD);
    INSERT_RELATION(ADJACENT, R4, R5),  INSERT_RELATION(ADJACENT, FD, FE);
    INSERT_RELATION(ADJACENT, R5, R6),  INSERT_RELATION(ADJACENT, FE, FF);
    INSERT_RELATION(ADJACENT, R6, R7),  INSERT_RELATION(ADJACENT, FF, FG);
    INSERT_RELATION(ADJACENT, R7, R8),  INSERT_RELATION(ADJACENT, FG, FH);
}
